// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGmBEiH8myBssB0BwYSBlFSEx0UsPOCM',
    appId: '1:346798165481:web:bee9802cfdbdff320bcf78',
    messagingSenderId: '346798165481',
    projectId: 'ryder-5cc3c',
    authDomain: 'ryder-5cc3c.firebaseapp.com',
    storageBucket: 'ryder-5cc3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGmBEiH8myBssB0BwYSBlFSEx0UsPOCM',
    appId: '1:346798165481:android:bee9802cfdbdff320bcf78',
    messagingSenderId: '346798165481',
    projectId: 'ryder-5cc3c',
    storageBucket: 'ryder-5cc3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZGmBEiH8myBssB0BwYSBlFSEx0UsPOCM',
    appId: '1:346798165481:ios:bee9802cfdbdff320bcf78', // This might need updating for iOS
    messagingSenderId: '346798165481',
    projectId: 'ryder-5cc3c',
    storageBucket: 'ryder-5cc3c.firebasestorage.app',
    iosBundleId: 'com.nikkhilpareek.ryder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZGmBEiH8myBssB0BwYSBlFSEx0UsPOCM',
    appId: '1:346798165481:ios:bee9802cfdbdff320bcf78', // This might need updating for macOS
    messagingSenderId: '346798165481',
    projectId: 'ryder-5cc3c',
    storageBucket: 'ryder-5cc3c.firebasestorage.app',
    iosBundleId: 'com.nikkhilpareek.ryder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGmBEiH8myBssB0BwYSBlFSEx0UsPOCM',
    appId: '1:346798165481:web:bee9802cfdbdff320bcf78', // This might need updating for Windows
    messagingSenderId: '346798165481',
    projectId: 'ryder-5cc3c',
    authDomain: 'ryder-5cc3c.firebaseapp.com',
    storageBucket: 'ryder-5cc3c.firebasestorage.app',
  );
}